services:
  php:
    build: .
    container_name: tpl3-php
    volumes:
      - .:/var/www/html
    networks:
      - tpl3-network

  nginx:
    image: nginx:alpine
    container_name: tpl3-nginx
    ports:
      - "8086:80"
      
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - tpl3-network

  docker_iibs:
    image: mysql:8.4
    container_name: docker_iibs
    environment:
      MYSQL_ROOT_PASSWORD: passer
      MYSQL_DATABASE: iibs
    ports:
      - "3306:3306"
    volumes:
      - db_data_iibs:/var/lib/mysql 
    networks:
      - tpl3-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_iibs
    environment:
      PMA_HOST: docker_iibs
      PMA_USER: root
      PMA_PASSWORD: passer
    ports:
      - "8080:80"
    depends_on:
      - docker_iibs
    networks:
      - tpl3-network

networks:
  tpl3-network:
    driver: bridge
